### ISSUE TITLE
Wrong link under 26.9

### ISSUE THREAD

**Issue by macie1** [MansoorMajeed/devops-from-scratch#5]
https://github.com/MansoorMajeed/devops-from-scratch/blob/master/episodes/26-jenkins-install-first-pipeline.md#step-9---configuring-ssl

The link is broken under 9th step, I think it should be:
https://github.com/MansoorMajeed/devops-from-scratch/blob/master/episodes/24-securing-nginx-free-ssl-letsencrypt.md

cheers.

**Comment by MansoorMajeed** [comment]
Hey @macie1, thanks a lot for pointing it out. Fixed
